version: '3.8'
services:
  ors-app:
    container_name: fullstack_ors_app
    ports:
      - 9090:8080
      - 9001:9001
    image: openrouteservice/openrouteservice:latest
    user: "${ORS_UID:-0}:${ORS_GID:-0}"
    volumes:
      - ./MapService/graphs:/ors-core/data/graphs
      - ./MapService/elevation_cache:/ors-core/data/elevation_cache
      - ./MapService/logs/ors:/var/log/ors
      - ./MapService/logs/tomcat:/usr/local/tomcat/logs
      - ./MapService/conf:/ors-conf
      - ./MapService/missouri.pbf:/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
