version: '3.8'
services:
  frontend:
    container_name: fullstack_frontend_container
    build:
      context: ./frontend
      args:
        - TILESERVICE=${TILESERVICE:-http://localhost:8100/tile/{z}/{x}/{y}.png}
        - BASEAPIPATH=${BASEAPIPATH:-http://localhost:8090}
    restart: always
    ports:
      - "4200:80"
volumes:
        capybaradbdata:
                driver: local
networks:
  default:
    name: docker-capybara-network