version: '3.8'
services:
  map:
    environment:
      - ALLOW_CORS=enabled
    image: overv/openstreetmap-tile-server:1.3.10
    volumes:
      - capy-openstreetmap-data:/var/lib/postgresql/12/main
    ports:
      - "8100:80"
    command: "run"
  frontend:
    container_name: fullstack_frontend_container
    build:
      context: ./frontend
      args:
        - TILESERVICE=${TILESERVICE:-http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png}
        - BASEAPIPATH=${BASEAPIPATH:-http://localhost:8090}
    restart: always
    ports:
      - "4200:80"

volumes:
  capy-openstreetmap-data:
    external: true

networks:
  default:
    name: docker-capybara-network