version: '3.8'
services:
  map:
    environment:
      - ALLOW_CORS=enabled
    image: overv/openstreetmap-tile-server:1.3.10
    volumes:
      - capy-openstreetmap-data:/var/lib/postgresql/12/main
    ports:
      - "8100:80"
    command: "run"

volumes:
  capy-openstreetmap-data:
    external: true

networks:
  default:
    name: docker-capybara-network