version: '3.8'
services:
  pgadmin:
    container_name: fullstack_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: capybara@admin.com
      PGADMIN_DEFAULT_PASSWORD: capy
    ports:
      - "5050:80"
  backend:
    container_name: fullstack_backend_container
    build: 
      context: ./backend
      # Uncomment below for buildkit, use COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
      #dockerfile: cache.Dockerfile
    restart: always
    ports:
      - "8090:8090"

volumes:
        capybaradbdata:
                driver: local
networks:
  default:
    name: docker-capybara-network