version: '3.8'
services:
  backend:
    container_name: fullstack_backend_container
    build: 
      context: ./backend
      args:
        - DATABASE_STRING=${DATABASE_STRING:-jdbc:postgresql://fullstack_pg_container:5432/capybara_db}
        - DATABASE_USER=${DATABASE_USER:-capy} 
        - DATABASE_PASSWD=${DATABASE_PASSWD:-capy}
        - ORS_KEY=${ORS_KEY}
    restart: always
    ports:
      - "8090:8090"
volumes:
        capybaradbdata:
                driver: local
networks:
  default:
    name: docker-capybara-network