version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
            - capybaradbdata:/var/lib/postgresql/data
            - ./sql-scripts/full-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: capy
      POSTGRES_PASSWORD: capy
      POSTGRES_DB: capybara_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: capybara@admin.com
      PGADMIN_DEFAULT_PASSWORD: capy
    ports:
      - "5050:80"

volumes:
        capybaradbdata:
                driver: local

networks:
  default:
    name: docker-capybara-network