plugin: openapi
specFile: spec.yml 

resources:
  - path: /buildings/
    method: get
    response:
      staticFile: mocked-data/buildings.json
  - path: /graph-nodes/
    method: get
    response:
      staticFile: mocked-data/nodes.json
  - path: /graph-edges/
    method: get
    response:
      staticFile: mocked-data/edges.json
  - path: /doors/
    method: get
    response:
      staticFile: mocked-data/doors.json