name: Backend PR Check

on:
  pull_request:
    paths: 'backend/**'
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: capybara_backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd backend && docker build . --file Dockerfile --build-arg ORS_KEY=${{secrets.ORS_KEY}} --build-arg DATABASE_STRING=${{secrets.DATABASE_STRING}} --build-arg DATABASE_USER=${{secrets.DATABASE_USER}} --build-arg DATABASE_PASSWD=${{secrets.DATABASE_PASSWD}} --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"