name: Build Backend Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create OpenRouteService file
      env:
        OPEN_ROUTE_SERVICE_FILE: ${{secrets.OPEN_ROUTE_SERVICE_KEYS}}
      run: |
        echo "$OPEN_ROUTE_SERVICE_FILE" > ./backend/docker-config/openrouteservice.properties
       
    - name: Build the Docker image
      run: cd backend && docker build . --file Dockerfile --tag capybara-backend:$(date +%s)
