name: Frontend PR Check

on:
  pull_request:
    paths: 'frontend/**'
    branches: [ main ]
  workflow_dispatch:
env:
  IMAGE_NAME: capybara_frontend

jobs:
  frontend-build-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd frontend && docker build . --file Dockerfile --build-arg TILESERVICE=${{ secrets.TILESERVICE }} --build-arg MAPAPIKEY=${{ secrets.MAPAPIKEY }} --build-arg BASEAPIPATH=${{ secrets.BASEAPIPATH }} --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"