name: Frontend PR Check

on:
  pull_request:
    paths: 'frontend/**'
    branches: [ main ]
  workflow_dispatch:
env:
  IMAGE_NAME: capybara_frontend

jobs:
  frontend-build-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - name: Install Packages
      run: |
        cd frontend/CapybaraApp
        npm install
    - name: Create Docker Config 
      run: cd frontend && ./create-docker-env.sh
      env:
        TILESERVICE: ${{ secrets.TILESERVICE }}
        MAPAPIKEY: ${{ secrets.MAPAPIKEY }}
        BASEAPIPATH: ${{ secrets.BASEAPIPATH }}
    - name: Build the Angular Frontend
      run: cd frontend/CapybaraApp && npm run build -- --configuration=docker
    - name: Build the Docker image
      run: cd frontend && docker build . --file Dockerfile-slim --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"